;; Control: read lengths that are not a multiple of 4 return ERR_RANGE (-1)
;; instead of reaching wgpu's copy validation.
(module
  (import "env" "memory" (memory 1 1))
  (import "wasmer_gpu_v0" "buffer_upload" (func $buffer_upload (param i32 i32) (result i32)))
  (import "wasmer_gpu_v0" "buffer_read" (func $buffer_read (param i32 i32 i32) (result i32)))
  (import "wasmer_gpu_v0" "buffer_release" (func $buffer_release (param i32) (result i32)))
  (import "wasmer_gpu_v0" "pipeline_create" (func $pipeline_create (param i32 i32) (result i32)))
  (import "wasmer_gpu_v0" "pipeline_dispatch" (func $pipeline_dispatch (param i32 i32 i32 i32 i32) (result i32)))
  (import "wasmer_gpu_v0" "pipeline_release" (func $pipeline_release (param i32) (result i32)))

  (func $_start (export "_start") (result i32)
    (local $buffer i32)
    (local $status3 i32)
    (local $status6 i32)
    (local.set $buffer (call $buffer_upload (i32.const 0) (i32.const 16)))
    (if (i32.lt_s (local.get $buffer) (i32.const 0))
      (then (return (local.get $buffer)))
    )
    (local.set $status3 (call $buffer_read (local.get $buffer) (i32.const 16) (i32.const 3)))
    (local.set $status6 (call $buffer_read (local.get $buffer) (i32.const 16) (i32.const 6)))
    (drop (call $buffer_release (local.get $buffer)))
    (if (i32.ne (local.get $status3) (i32.const -1))
      (then (return (i32.const 1)))
    )
    (if (i32.ne (local.get $status6) (i32.const -1))
      (then (return (i32.const 2)))
    )
    (i32.const 0)
  )
)
